# Label issues related to bugs
bug:
    - '*bug*'
    - '*error*'
    - '*fail*'
    - '*failure*'
    - '*issue*'
    - '*crash*'
    - '*problem*'
    - '*fault*'
    - '*defect*'
    - '*break*'

# Label issues related to new features or enhancements
enhancement:
    - '*enhancement*'
    - '*feature*'
    - '*improve*'
    - '*upgrade*'
    - '*add*'
    - '*implement*'
    - '*new feature*'
    - '*new functionality*'

# Label issues related to documentation
documentation:
    - '*doc*'
    - '*docs*'
    - '*readme*'
    - '*wiki*'
    - '*documentation*'
    - '*guide*'
    - '*manual*'
    - '*instruction*'

# Label issues related to performance improvements
performance:
    - '*performance*'
    - '*speed*'
    - '*optimize*'
    - '*slow*'
    - '*lag*'
    - '*efficient*'
    - '*latency*'
    - '*throughput*'
    - '*bottleneck*'

# Label issues related to security concerns
security:
    - '*security*'
    - '*vulnerability*'
    - '*exploit*'
    - '*attack*'
    - '*secure*'
    - '*encryption*'
    - '*breach*'
    - '*hack*'
    - '*malware*'
    - '*threat*'
    - '*safety*'

# Label issues related to testing
test:
    - '*test*'
    - '*testing*'
    - '*unittest*'
    - '*integration*'
    - '*e2e*'
    - '*coverage*'
    - '*test case*'
    - '*regression*'
    - '*qa*'
    - '*validation*'

# Label issues related to user interface or design
design:
    - '*ui*'
    - '*ux*'
    - '*interface*'
    - '*design*'
    - '*layout*'
    - '*style*'
    - '*aesthetic*'
    - '*visual*'
    - '*user experience*'
    - '*user interface*'

# Label issues related to configuration or setup
configuration:
    - '*config*'
    - '*configuration*'
    - '*setup*'
    - '*install*'
    - '*installation*'
    - '*environment*'
    - '*settings*'
    - '*initialization*'
    - '*deployment*'
    - '*setup guide*'

# Label issues related to dependencies or third-party libraries
dependencies:
    - '*dependency*'
    - '*dependencies*'
    - '*package*'
    - '*library*'
    - '*upgrade*'
    - '*update*'
    - '*module*'
    - '*plugin*'
    - '*third-party*'
    - '*external*'
    - '*vendor*'

# Label issues that are questions or require further discussion
question:
    - '*question*'
    - '*inquiry*'
    - '*how to*'
    - '*help*'
    - '*support*'
    - '*clarification*'
    - '*query*'
    - '*why*'
    - '*what*'
    - '*who*'
    - '*where*'

# Label issues related to accessibility concerns
accessibility:
    - '*accessibility*'
    - '*a11y*'
    - '*inclusive*'
    - '*assistive*'
    - '*screen reader*'
    - '*accessible*'
    - '*disability*'
    - '*inclusive design*'
    - '*equal access*'
